### ISSUE TITLE
Гайды для новичков

### ISSUE THREAD

**Issue by zhoreeq** [yggdrasil-mesh/development#2]
Какие есть идеи для гайдов?

**Comment by zhoreeq** [comment]
Первое, что приходит в голову, сделать раздел "Быстрый старт" 

- как быстро вкатиться в меш для винды
- гайд для openwrt
- гайд для vps

**Comment by Revertron** [comment]
- использование нескольких айпишников из 300::/8 для размещения своих сервисов
- использование ДНС, хоть и временного
- настройка фаирволла, так как теперь у всех "реальный" айпишник
